version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Worksoft1234*"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - worksoft-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - worksoft-network

  api:
    build:
      context: ./src/backend
      dockerfile: WorksoftTaskTracker.API/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mssql,1433;Database=WorksoftTaskTracker;User Id=sa;Password=Worksoft1234*;TrustServerCertificate=True;
      - Redis__ConnectionString=redis:6379
      - Redis__InstanceName=WorksoftCache
      - Jwt__SecretKey=worksoft-super-secret-jwt-key-minimum-32-chars
      - Jwt__Issuer=WorksoftTaskTracker
      - Jwt__Audience=WorksoftTaskTrackerClient
      - Jwt__ExpireMinutes=60
    depends_on:
      - mssql
      - redis
    networks:
      - worksoft-network

#   frontend:
#     build:
#       context: ./src/frontend
#       dockerfile: Dockerfile
#     ports:
#       - "3000:80"
#     depends_on:
#       - api
#     networks:
#       - worksoft-network

networks:
  worksoft-network:
    driver: bridge

volumes:
  mssql_data: