apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: worksoft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: worksoft-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: worksoft
spec:
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 80
  type: NodePort