apiVersion: v1
kind: Secret
metadata:
  name: worksoft-secrets
  namespace: worksoft
type: Opaque
stringData:
  SA_PASSWORD: "Wstaj2026Serkan"
  CONNECTION_STRING: "Server=mssql,1433;Database=WorksoftTaskTracker;User Id=sa;Password=Wstaj2026Serkan;TrustServerCertificate=True;"
  JWT_SECRET_KEY: "worksoft-super-secret-jwt-key-minimum-32-chars"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: worksoft-config
  namespace: worksoft
data:
  REDIS_CONNECTION: "redis:6379"
  REDIS_INSTANCE: "WorksoftCache"
  JWT_ISSUER: "WorksoftTaskTracker"
  JWT_AUDIENCE: "WorksoftTaskTrackerClient"
  JWT_EXPIRE_MINUTES: "60"